// +build ignore

package main

import (
	"fmt"
	"io/ioutil"
	"log"
	"os"
	"text/template"
	"time"
)

func main() {
	f, err := os.Create("entity.go")
	exit(err)
	bytes := getEntityFile()

	packageTemplate.Execute(f, struct {
		Timestamp time.Time
		Entity    string
	}{
		Timestamp: time.Now(),
		Entity:    fmt.Sprintf("%q", bytes),
	})
}

func exit(e error) {
	if e != nil {
		log.Fatal(e)
	}
}

func getEntityFile() []byte {
	entityfile := os.Getenv("BW2_DEFAULT_ENTITY")
	fmt.Println(entityfile)
	bytes, err := ioutil.ReadFile(entityfile)
	exit(err)
	return bytes
}

var packageTemplate = template.Must(template.New("").Parse(`// go generate
// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by go:generate at
// {{ .Timestamp }}
package main

var _entity = {{ .Entity }}
`))
